# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"

# command to run tests
script: nosetests --with-coverage --cover-package=kubernetes.config,kubernetes.watch --cover-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
