# ref: https://docs.travis-ci.com/user/languages/python
language: python
sudo: true
services:
  - docker
env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=py27-functional
  - TOXENV=py35-functional
  - TOXENV=update-pep8
  - TOXENV=docs
  - TOXENV=coverage,codecov

before_install:
  - sudo add-apt-repository ppa:0k53d-karl-f830m/hitch -y
  - sudo apt-get -qq update
  - sudo apt-get install hitch

install:
  - pip install tox
  - hitch --frontend=[*]:8443 --backend=[localhost]:8080 --daemon $TRAVIS_BUILD_DIR/scripts/example.pem

script:
  - tox
